[project]
name = "picogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire",
    "numpy",
    "regex",
    "requests",
    "tensorflow>=2.19.0",
    "tqdm",
]
